# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  clipboard-app:
    image: clipboard
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://clipboard-postgresql:5432/clipboard
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://clipboard-postgresql:5432/clipboard
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8888:8080
  clipboard-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/jhipster/clipboard/postgresql/:/var/lib/postgresql/data/
      - /opt/clipboard:/opt/clipboard
    environment:
      - POSTGRES_DB=clipboard
      - POSTGRES_USER=cb_dbuser
      - POSTGRES_PASSWORD=ym39hSrWH5NwJuYDqsLpCQ
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
